/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VodaRouteImport } from './routes/voda'
import { Route as TillWakalaRouteImport } from './routes/till-wakala'
import { Route as SmeBundleRouteImport } from './routes/sme-bundle'
import { Route as RouterInternetRouteImport } from './routes/router-internet'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as MipangilioRouteImport } from './routes/mipangilio'
import { Route as MalipoRouteImport } from './routes/malipo'
import { Route as MaelezoTillZaWakalaRouteImport } from './routes/maelezo-till-za-wakala'
import { Route as MaelezoSmeBundlesRouteImport } from './routes/maelezo-sme-bundles'
import { Route as MaelezoRouterUnlimitedRouteImport } from './routes/maelezo-router-unlimited'
import { Route as MaelezoOnlineApplicationsRouteImport } from './routes/maelezo-online-applications'
import { Route as MaelezoLipaRouteImport } from './routes/maelezo-lipa'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LipaNambaRouteImport } from './routes/lipa-namba'
import { Route as FuatiliaRouteImport } from './routes/fuatilia'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'

const VodaRoute = VodaRouteImport.update({
  id: '/voda',
  path: '/voda',
  getParentRoute: () => rootRouteImport,
} as any)
const TillWakalaRoute = TillWakalaRouteImport.update({
  id: '/till-wakala',
  path: '/till-wakala',
  getParentRoute: () => rootRouteImport,
} as any)
const SmeBundleRoute = SmeBundleRouteImport.update({
  id: '/sme-bundle',
  path: '/sme-bundle',
  getParentRoute: () => rootRouteImport,
} as any)
const RouterInternetRoute = RouterInternetRouteImport.update({
  id: '/router-internet',
  path: '/router-internet',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const MipangilioRoute = MipangilioRouteImport.update({
  id: '/mipangilio',
  path: '/mipangilio',
  getParentRoute: () => rootRouteImport,
} as any)
const MalipoRoute = MalipoRouteImport.update({
  id: '/malipo',
  path: '/malipo',
  getParentRoute: () => rootRouteImport,
} as any)
const MaelezoTillZaWakalaRoute = MaelezoTillZaWakalaRouteImport.update({
  id: '/maelezo-till-za-wakala',
  path: '/maelezo-till-za-wakala',
  getParentRoute: () => rootRouteImport,
} as any)
const MaelezoSmeBundlesRoute = MaelezoSmeBundlesRouteImport.update({
  id: '/maelezo-sme-bundles',
  path: '/maelezo-sme-bundles',
  getParentRoute: () => rootRouteImport,
} as any)
const MaelezoRouterUnlimitedRoute = MaelezoRouterUnlimitedRouteImport.update({
  id: '/maelezo-router-unlimited',
  path: '/maelezo-router-unlimited',
  getParentRoute: () => rootRouteImport,
} as any)
const MaelezoOnlineApplicationsRoute =
  MaelezoOnlineApplicationsRouteImport.update({
    id: '/maelezo-online-applications',
    path: '/maelezo-online-applications',
    getParentRoute: () => rootRouteImport,
  } as any)
const MaelezoLipaRoute = MaelezoLipaRouteImport.update({
  id: '/maelezo-lipa',
  path: '/maelezo-lipa',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LipaNambaRoute = LipaNambaRouteImport.update({
  id: '/lipa-namba',
  path: '/lipa-namba',
  getParentRoute: () => rootRouteImport,
} as any)
const FuatiliaRoute = FuatiliaRouteImport.update({
  id: '/fuatilia',
  path: '/fuatilia',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/fuatilia': typeof FuatiliaRoute
  '/lipa-namba': typeof LipaNambaRoute
  '/login': typeof LoginRoute
  '/maelezo-lipa': typeof MaelezoLipaRoute
  '/maelezo-online-applications': typeof MaelezoOnlineApplicationsRoute
  '/maelezo-router-unlimited': typeof MaelezoRouterUnlimitedRoute
  '/maelezo-sme-bundles': typeof MaelezoSmeBundlesRoute
  '/maelezo-till-za-wakala': typeof MaelezoTillZaWakalaRoute
  '/malipo': typeof MalipoRoute
  '/mipangilio': typeof MipangilioRoute
  '/reports': typeof ReportsRoute
  '/router-internet': typeof RouterInternetRoute
  '/sme-bundle': typeof SmeBundleRoute
  '/till-wakala': typeof TillWakalaRoute
  '/voda': typeof VodaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/fuatilia': typeof FuatiliaRoute
  '/lipa-namba': typeof LipaNambaRoute
  '/login': typeof LoginRoute
  '/maelezo-lipa': typeof MaelezoLipaRoute
  '/maelezo-online-applications': typeof MaelezoOnlineApplicationsRoute
  '/maelezo-router-unlimited': typeof MaelezoRouterUnlimitedRoute
  '/maelezo-sme-bundles': typeof MaelezoSmeBundlesRoute
  '/maelezo-till-za-wakala': typeof MaelezoTillZaWakalaRoute
  '/malipo': typeof MalipoRoute
  '/mipangilio': typeof MipangilioRoute
  '/reports': typeof ReportsRoute
  '/router-internet': typeof RouterInternetRoute
  '/sme-bundle': typeof SmeBundleRoute
  '/till-wakala': typeof TillWakalaRoute
  '/voda': typeof VodaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/fuatilia': typeof FuatiliaRoute
  '/lipa-namba': typeof LipaNambaRoute
  '/login': typeof LoginRoute
  '/maelezo-lipa': typeof MaelezoLipaRoute
  '/maelezo-online-applications': typeof MaelezoOnlineApplicationsRoute
  '/maelezo-router-unlimited': typeof MaelezoRouterUnlimitedRoute
  '/maelezo-sme-bundles': typeof MaelezoSmeBundlesRoute
  '/maelezo-till-za-wakala': typeof MaelezoTillZaWakalaRoute
  '/malipo': typeof MalipoRoute
  '/mipangilio': typeof MipangilioRoute
  '/reports': typeof ReportsRoute
  '/router-internet': typeof RouterInternetRoute
  '/sme-bundle': typeof SmeBundleRoute
  '/till-wakala': typeof TillWakalaRoute
  '/voda': typeof VodaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/fuatilia'
    | '/lipa-namba'
    | '/login'
    | '/maelezo-lipa'
    | '/maelezo-online-applications'
    | '/maelezo-router-unlimited'
    | '/maelezo-sme-bundles'
    | '/maelezo-till-za-wakala'
    | '/malipo'
    | '/mipangilio'
    | '/reports'
    | '/router-internet'
    | '/sme-bundle'
    | '/till-wakala'
    | '/voda'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/fuatilia'
    | '/lipa-namba'
    | '/login'
    | '/maelezo-lipa'
    | '/maelezo-online-applications'
    | '/maelezo-router-unlimited'
    | '/maelezo-sme-bundles'
    | '/maelezo-till-za-wakala'
    | '/malipo'
    | '/mipangilio'
    | '/reports'
    | '/router-internet'
    | '/sme-bundle'
    | '/till-wakala'
    | '/voda'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dashboard'
    | '/fuatilia'
    | '/lipa-namba'
    | '/login'
    | '/maelezo-lipa'
    | '/maelezo-online-applications'
    | '/maelezo-router-unlimited'
    | '/maelezo-sme-bundles'
    | '/maelezo-till-za-wakala'
    | '/malipo'
    | '/mipangilio'
    | '/reports'
    | '/router-internet'
    | '/sme-bundle'
    | '/till-wakala'
    | '/voda'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  DashboardRoute: typeof DashboardRoute
  FuatiliaRoute: typeof FuatiliaRoute
  LipaNambaRoute: typeof LipaNambaRoute
  LoginRoute: typeof LoginRoute
  MaelezoLipaRoute: typeof MaelezoLipaRoute
  MaelezoOnlineApplicationsRoute: typeof MaelezoOnlineApplicationsRoute
  MaelezoRouterUnlimitedRoute: typeof MaelezoRouterUnlimitedRoute
  MaelezoSmeBundlesRoute: typeof MaelezoSmeBundlesRoute
  MaelezoTillZaWakalaRoute: typeof MaelezoTillZaWakalaRoute
  MalipoRoute: typeof MalipoRoute
  MipangilioRoute: typeof MipangilioRoute
  ReportsRoute: typeof ReportsRoute
  RouterInternetRoute: typeof RouterInternetRoute
  SmeBundleRoute: typeof SmeBundleRoute
  TillWakalaRoute: typeof TillWakalaRoute
  VodaRoute: typeof VodaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/voda': {
      id: '/voda'
      path: '/voda'
      fullPath: '/voda'
      preLoaderRoute: typeof VodaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/till-wakala': {
      id: '/till-wakala'
      path: '/till-wakala'
      fullPath: '/till-wakala'
      preLoaderRoute: typeof TillWakalaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sme-bundle': {
      id: '/sme-bundle'
      path: '/sme-bundle'
      fullPath: '/sme-bundle'
      preLoaderRoute: typeof SmeBundleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/router-internet': {
      id: '/router-internet'
      path: '/router-internet'
      fullPath: '/router-internet'
      preLoaderRoute: typeof RouterInternetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mipangilio': {
      id: '/mipangilio'
      path: '/mipangilio'
      fullPath: '/mipangilio'
      preLoaderRoute: typeof MipangilioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/malipo': {
      id: '/malipo'
      path: '/malipo'
      fullPath: '/malipo'
      preLoaderRoute: typeof MalipoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maelezo-till-za-wakala': {
      id: '/maelezo-till-za-wakala'
      path: '/maelezo-till-za-wakala'
      fullPath: '/maelezo-till-za-wakala'
      preLoaderRoute: typeof MaelezoTillZaWakalaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maelezo-sme-bundles': {
      id: '/maelezo-sme-bundles'
      path: '/maelezo-sme-bundles'
      fullPath: '/maelezo-sme-bundles'
      preLoaderRoute: typeof MaelezoSmeBundlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maelezo-router-unlimited': {
      id: '/maelezo-router-unlimited'
      path: '/maelezo-router-unlimited'
      fullPath: '/maelezo-router-unlimited'
      preLoaderRoute: typeof MaelezoRouterUnlimitedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maelezo-online-applications': {
      id: '/maelezo-online-applications'
      path: '/maelezo-online-applications'
      fullPath: '/maelezo-online-applications'
      preLoaderRoute: typeof MaelezoOnlineApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maelezo-lipa': {
      id: '/maelezo-lipa'
      path: '/maelezo-lipa'
      fullPath: '/maelezo-lipa'
      preLoaderRoute: typeof MaelezoLipaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lipa-namba': {
      id: '/lipa-namba'
      path: '/lipa-namba'
      fullPath: '/lipa-namba'
      preLoaderRoute: typeof LipaNambaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fuatilia': {
      id: '/fuatilia'
      path: '/fuatilia'
      fullPath: '/fuatilia'
      preLoaderRoute: typeof FuatiliaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  DashboardRoute: DashboardRoute,
  FuatiliaRoute: FuatiliaRoute,
  LipaNambaRoute: LipaNambaRoute,
  LoginRoute: LoginRoute,
  MaelezoLipaRoute: MaelezoLipaRoute,
  MaelezoOnlineApplicationsRoute: MaelezoOnlineApplicationsRoute,
  MaelezoRouterUnlimitedRoute: MaelezoRouterUnlimitedRoute,
  MaelezoSmeBundlesRoute: MaelezoSmeBundlesRoute,
  MaelezoTillZaWakalaRoute: MaelezoTillZaWakalaRoute,
  MalipoRoute: MalipoRoute,
  MipangilioRoute: MipangilioRoute,
  ReportsRoute: ReportsRoute,
  RouterInternetRoute: RouterInternetRoute,
  SmeBundleRoute: SmeBundleRoute,
  TillWakalaRoute: TillWakalaRoute,
  VodaRoute: VodaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
